/* code generated by freemarker */
<#import "../global.ftl" as common>
package ${packageName}.service;

import ${packageName}.dao.${entityName}DAO;
import ${packageName}.model.dto.${entityName}PageDTO;
import ${packageName}.model.dto.${entityName}QueryDTO;
import ${packageName}.model.entity.${entityName};
import com.ums.common.tools.basic.UUID;
import com.ums.datasource.util.spring.PageData;
import com.ums.service.common.exception.BizIllegalArgumentException;
import com.ums.service.common.exception.BizInternalServerException;
import com.ums.service.common.exception.BizResourceNotFoundException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.ObjectUtils;

import java.util.List;

@Service
@Slf4j
@RequiredArgsConstructor
public class ${entityName}Service {

    private final ${entityName}DAO ${entityName?uncap_first}DAO;

    public PageData<${entityName}> queryPageData(${entityName}PageDTO pageDTO) {
        // 参数校验
        if (pageDTO == null) {
            throw new BizIllegalArgumentException("查询${entityNameCN}，参数不能为空");
        }

        PageData<${entityName}> pageData = ${entityName?uncap_first}DAO.queryPageData(pageDTO);

        log.info("分页查询${entityNameCN}完成, 总记录数: {}", pageData.getRowCount());
        return pageData;
    }

    public List<${entityName}> queryList(${entityName}QueryDTO queryDTO) {
        // 参数校验
        if (queryDTO == null) {
            throw new BizIllegalArgumentException("查询${entityNameCN}，参数不能为空");
        }

        // 调用DAO层进行分页查询
        List<${entityName}> list = ${entityName?uncap_first}DAO.queryList(queryDTO);

        log.info("列表查询${entityNameCN}完成, 总记录数: {}", list.size());
        return list;
    }

    public ${entityName} queryById(String id) {
        try {
            if (ObjectUtils.isEmpty(id)) {
                throw new BizIllegalArgumentException("${entityNameCN}ID不能为空");
            }

            ${entityName} item = ${entityName?uncap_first}DAO.queryById(id);
            if (item == null) {
                log.error("${entityNameCN}不存在, id: " + id);
                throw new BizResourceNotFoundException("${entityNameCN}不存在或已被删除");
            }

            return item;

        } catch (Exception e) {
            log.error("查询错误", e);
            throw new BizInternalServerException("查询${entityNameCN}错误");
        }
    }

    public List<${entityName}> queryByIdList(List<String> idList) {
        // 参数校验
        if (ObjectUtils.isEmpty(idList)) {
            throw new BizIllegalArgumentException("查询${entityNameCN}，参数不能为空");
        }

        // 调用DAO层进行分页查询
        List<${entityName}> list = ${entityName?uncap_first}DAO.queryByIdList(idList);

        log.info("根据ID列表查询${entityNameCN}完成, 总记录数: {}", list.size());
        return list;
    }

    @Transactional(rollbackFor = Exception.class)
    public ${entityName} add(${entityName} ${entityName}) {
        try {
            if (ObjectUtils.isEmpty(${entityName})) {
                throw new BizIllegalArgumentException("保存${entityNameCN}，参数不能为空");
            }

            // TODO 参数校验

            // TODO 其他业务参数处理

            fillPrimaryKey(${entityName});

            ${entityName?uncap_first}DAO.add(${entityName});

            log.info("添加${entityNameCN}, id: {}", ${entityName}.get${common.getPrimaryName(fieldList)?cap_first}());
            return ${entityName};
        } catch (Exception e) {
            log.error("保存${entityNameCN}错误", e);
            throw new BizInternalServerException("保存${entityNameCN}错误");
        }
    }

    @Transactional(rollbackFor = Exception.class)
    public int addBatch(List<${entityName}> ${entityName}List) {
        try {
            if (ObjectUtils.isEmpty(${entityName}List)) {
                throw new BizIllegalArgumentException("批量添加${entityNameCN}，参数不能为空");
            }
            for (${entityName} item : ${entityName}List) {

                // TODO 参数校验

                // TODO 其他业务参数赋值

                fillPrimaryKey(item);
            }

            int insertColumn = ${entityName?uncap_first}DAO.add(${entityName}List.toArray(${entityName}[]::new));

            log.info("批量添加${entityNameCN} {} 条数据", insertColumn);
            return insertColumn;
        } catch (Exception e) {
            log.error("批量添加${entityNameCN}错误", e);
            throw new BizInternalServerException("批量添加${entityNameCN}错误");
        }
    }

    @Transactional(rollbackFor = Exception.class)
    public ${entityName} update(${entityName} ${entityName?uncap_first}) {
        try {
            if (ObjectUtils.isEmpty(${entityName?uncap_first})) {
                throw new BizIllegalArgumentException("编辑${entityNameCN}，参数不能为空");
            }

            // TODO 参数校验

            ${entityName} ${entityName?uncap_first}Tmp = queryById(${entityName?uncap_first}.get${common.getPrimaryName(fieldList)?cap_first}());
            if (${entityName?uncap_first}Tmp == null) {
                throw new BizResourceNotFoundException("${entityNameCN}不存在或已被删除");
            }

            ${entityName?uncap_first}DAO.update(${entityName?uncap_first});
            return ${entityName?uncap_first};
        } catch (Exception e) {
            log.error("编辑数据错误", e);
            throw new BizInternalServerException("编辑${entityNameCN}错误");
        }
    }


    @Transactional(rollbackFor = Exception.class)
    public int updateBatch(List<${entityName}> ${entityName?uncap_first}List) {
        try {
            if (ObjectUtils.isEmpty(${entityName?uncap_first}List)) {
                throw new BizIllegalArgumentException("批量编辑${entityNameCN}，参数不能为空");
            }

            // TODO 参数校验

            List<${entityName}> ids = ${entityName?uncap_first}DAO.queryByIdList(${entityName?uncap_first}List
                .stream()
                .filter(o -> !ObjectUtils.isEmpty(o.get${common.getPrimaryName(fieldList)?cap_first}()))
                .map(${entityName}::get${common.getPrimaryName(fieldList)?cap_first})
                .toList());

            if (ids.size() != ${entityName?uncap_first}List.size()) {
                throw new BizResourceNotFoundException("${entityNameCN}存在的个数" + ids.size() + " , 不存在的个数" + (${entityName?uncap_first}List.size() - ids.size()));
            }

            int column = ${entityName?uncap_first}DAO.update(${entityName?uncap_first}List.toArray(${entityName}[]::new));
            log.info("批量编辑${entityNameCN} {} 条数据", column);
            return column;
        } catch (Exception e) {
            log.error("批量编辑${entityNameCN}错误", e);
            throw new BizInternalServerException("批量编辑${entityNameCN}错误");
        }
    }

    @Transactional(rollbackFor = Exception.class)
    public ${entityName} delete(String id) {
        if (ObjectUtils.isEmpty(id)) {
            throw new BizIllegalArgumentException("删除${entityNameCN}，ID不能为空");
        }

        ${entityName} ${entityName?uncap_first} = queryById(id);
        if(${entityName?uncap_first} == null) {
            throw new BizResourceNotFoundException("${entityNameCN}不存在或已被删除");
        }
        try {
            ${entityName?uncap_first}DAO.deleteById(id);
            return ${entityName?uncap_first};
        } catch (Exception e) {
            log.error("删除${entityNameCN}错误", e);
            throw new BizInternalServerException("删除${entityNameCN}错误");
        }
    }

    @Transactional(rollbackFor = Exception.class)
    public int deleteBatch(List<String> idList) {
        try {
            if (ObjectUtils.isEmpty(idList)) {
                throw new BizIllegalArgumentException("批量删除${entityNameCN}，参数不能为空");
            }

            int column = ${entityName?uncap_first}DAO.deleteById(idList.toArray(String[]::new));
            log.info("批量删除${entityNameCN} {} 条数据", column);
            return column;
        } catch (Exception e) {
            log.error("批量删除${entityNameCN}错误", e);
            throw new BizInternalServerException("批量删除${entityNameCN}错误");
        }
    }

    /*================*/
    /* private method */
    /*================*/

    private void fillPrimaryKey(${entityName} entity) {
        entity.set${common.getPrimaryName(fieldList)?cap_first}(UUID.randomUUID());
    }

}