/* code generated by freemarker */
package ${packageName}.service.impl;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import ${packageName}.service.${entityName}Service;
import ${packageName}.model.${entityName}DAO;

@Service
@Slf4j
@RequiredArgsConstructor
public class ${entityName}ServiceImpl implements ${entityName}Service {
    private final ${entityName}DAO ${entityName?uncap_first}DAO;

    /**
    * @param ${entityName} 更新或插入对应实体
    */
    @Overwrite
    private ${entityName} queryById(<#list fieldList as fieldItem ><#if fieldItem.primaryKey>${fieldItem.type} id</#if></#list>) {
        return ${entityName?uncap_first}DAO.queryById(id);
    }

    /**
    * @param ${entityName} 更新或插入对应实体
    */
    @Overwrite
    private int upsert(${entityName} ${entityName?uncap_first}) {
        if (queryById(<#list fieldList as fieldItem ><#if fieldItem.primaryKey>${entityName?uncap_first}.${fieldItem.name}</#if></#list>) == null) {
            return ${entityName?uncap_first}DAO.add(${entityName?uncap_first});
        } else {
            return ${entityName?uncap_first}DAO.update(${entityName?uncap_first});
        }
    }

    /**
    * @param id 根据主键id删除对应实体
    */
    @Overwrite
    private int delete(<#list fieldList as fieldItem><#if fieldItem.primaryKey>${fieldItem.type} id</#if></#list>) {
        return ${entityName?uncap_first}DAO.deleteById(id);
    }
}