spring:
  application:
    name: generator
  ai:
    mcp:
      server:
        name: generator-server
        version: 0.0.1
        type: SYNC
        stdio: true
        enabled: true
  main:
    banner-mode: off
    web-application-type: none
  freemarker:
    charset: UTF-8
logging:
  level:
    com: info
    org: info
  pattern:
    console:
  file:
    name: mcp-code-generate.log