spring:
  application:
    name: generator
  ai:
    mcp:
      server:
        name: generator-server
        version: 0.0.1
        type: SYNC
  main:
    banner-mode: off
    web-application-type: none