/* code generated by freemarker */
<#import "../global.ftl" as common>
package ${packageName}.repository;

import org.springframework.stereotype.Repository;

import ${packageName}.model.entity.${entityName};
import com.ums.datasource.util.spring.PageData;
import com.ums.datasource.util.BaseEntityDAO;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import java.util.List;

@Repository
public class ${entityName}DAO extends BaseEntityDAO<${entityName}> {
    public List<String> existsByIds(List<String> ids) {
        NamedParameterJdbcTemplate jdbcTemplate = new NamedParameterJdbcTemplate(getJdbcTemplate());
        String sql = """
            select ${common.getColumnPrimaryName(fieldList)} from ${tableName}
            where ${common.getColumnPrimaryName(fieldList)} in (:ids)
        """;
        MapSqlParameterSource params = new MapSqlParameterSource();
        params.addValue("ids", ids);
        return jdbcTemplate.queryForList(sql, params, String.class);
    }
}