/* code generated by freemarker */
<#import "../global.ftl" as common>
package ${packageName}.dao;

import ${packageName}.model.entity.${entityName};
import ${packageName}.model.dto.${entityName}PageDTO;
import ${packageName}.model.dto.${entityName}QueryDTO;
import ${packageName}.model.entity.${entityName};
import com.ultrasafe.smart.dataaccess.utils.SqlUtils;
import com.ums.datasource.util.BaseEntityDAO;
import com.ums.datasource.util.db.SqlUtil;
import com.ums.datasource.util.spring.PageData;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;

@Repository
public class ${entityName}DAO extends BaseEntityDAO<${entityName}> {
    @Autowired
    private SqlUtil sqlUtil;

    public PageData<${entityName}> queryPageData(${entityName}PageDTO pageDTO) {
        List<Object> params = new ArrayList<Object>();
        // TODO 业务SQL
        StringBuffer sql = new StringBuffer("""

        """);

        // TODO 参数拼装

        // 执行查询
        return super.queryPageData(params, sql.toString(), pageDTO.getPage(), pageDTO.getPageSize());
    }

    public List<${entityName}> queryList(${entityName}QueryDTO queryDTO) {
        List<Object> params = new ArrayList<Object>();
        // TODO 业务SQL
        StringBuffer sql = new StringBuffer("""

        """);

        // TODO 参数拼装

        // 执行查询
        return super.queryBySql(sql.toString(), params.toArray(new Object[]{}));
    }

    public List<${entityName}> queryByIdList(List<String> idList) {
        if (idList == null || idList.isEmpty()) {
            return new ArrayList<>();
        }

        String sql = "select * from ${tableName} where 1=1 " + SqlUtils.buildInConditionStr(idList.size(), "${common.getColumnPrimaryName(fieldList)}");
        return super.queryBySql(sql, idList.toArray());
    }
}