/* code generated by freemarker */
package ${packageName}.dao;

import org.springframework.stereotype.Repository;

import ${packageName}.model.Algorithm;
import com.ums.datasource.util.BaseEntityDAO;

@Repository
public class ${entityName}DAO extends BaseEntityDAO<${entityName}> {
}